networks:
  external:
    name: external
  internal:
    name: internal

volumes:
    mongo_data:

services:
    mongodb:
        container_name: shlong-mongo
        image : mongo:latest
        restart: unless-stopped
        env_file:
          - mongo.env
        networks:
          - internal
        volumes:
          - mongo_data:/data/db
        ports:
          - 27017:27017