networks:
  external:
    name: external
  internal:
    name: internal

services:
  web:
    container_name: shlong-web
    image: shlong-web:${SHLONG_WEB_VERSION:latest}
    restart: unless-stopped
    env_file:
      - .env
      - web.env
    networks:
      - external
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=external
      #
      - traefik.http.routers.shlong-web-http.rule=Host(`${SHLONG_WEB_FQDN}`)
      - traefik.http.routers.shlong-web-http.entrypoints=web
      - traefik.http.routers.shlong-web-http.middlewares=redirect-to-https
      - traefik.http.routers.shlong-web-http.service=shlong-web
      #
      - traefik.http.routers.shlong-web-https.rule=Host(`${SHLONG_WEB_FQDN}`)
      - traefik.http.routers.shlong-web-https.entrypoints=websecure
      - traefik.http.routers.shlong-web-https.tls=true
      - traefik.http.routers.shlong-web-https.tls.certresolver=letsencrypt
      - traefik.http.routers.shlong-api-https.service=shlong-web
      #
      - traefik.http.services.shlong-web.loadbalancer.server.port=3000

  api:
    container_name: shlong-api
    image: shlong-api:${SHLONG_API_VERSION:latest}
    restart: unless-stopped
    env_file:
      - .env
      - api.env
    networks:
      - external
      - internal
    expose:
      - 5000
      - 6000
    labels:
      - traefik.enable=true
      - traefik.docker.network=external
      #
      - traefik.http.routers.shlong-api-http.rule=Host(`${SHLONG_API_FQDN}`)
      - traefik.http.routers.shlong-api-http.entrypoints=web
      - traefik.http.routers.shlong-api-http.middlewares=redirect-to-https
      - traefik.http.routers.shlong-api-http.service=shlong-api
      #
      - traefik.http.routers.shlong-api-https.rule=Host(`${SHLONG_API_FQDN}`)
      - traefik.http.routers.shlong-api-https.entrypoints=websecure
      - traefik.http.routers.shlong-api-https.tls=true
      - traefik.http.routers.shlong-api-https.tls.certresolver=letsencrypt
      - traefik.http.routers.shlong-api-https.service=shlong-api
      - traefik.http.services.shlong-api.loadbalancer.server.port=5000
      #
      - traefik.http.routers.shlong-ws-https.rule=Host(`${SHLONG_WS_FQDN}`)
      - traefik.http.routers.shlong-ws-https.entrypoints=websecure
      - traefik.http.routers.shlong-ws-https.tls=true
      - traefik.http.routers.shlong-ws-https.tls.certresolver=letsencrypt
      - traefik.http.routers.shlong-ws-https.service=shlong-ws
      - traefik.http.services.shlong-ws.loadbalancer.server.port=6000
